### ISSUE TITLE
Persistence and reloading of conditional infos

### ISSUE THREAD

**Issue by koebi** [GIScience/graphhopper#61]
The source of this problem is [this issue](https://github.com/GIScience/openrouteservice/issues/1363) - probably to be fixed in `GraphHopperStorage.java`, L417 ff.
by appending to the `flush()`-method:

```
        if (conditionalAccess != null) {
            conditionalAccess.flush();
        }
        if (conditionalSpeed != null) {
            conditionalSpeed.flush();
        }
```

similar as is being done in the `close()`-method.

**Comment by MichaelsJP** [comment]
closed by #62
